substitutions:
  name: "e1-pd76-r5-v3"
  friendly_name: "JetHub E1-PD76-R5 v3"
  device_description: "JetHub E1-PD76-R5 v3"
  version: "1.0.0"

packages:
  base: !include include/e1-base.yaml
  board: !include include/e1-board-v3.yaml
  wifi: !include ../include/wifi.yaml
  onewire: !include include/e1-onewire.yaml

esphome:
  on_boot:
    priority: 600
    then:
      - script.execute: set_wifi_ap
