one_wire:
  id: one_wire1_id
  platform: gpio
  pin: GPIO15

sensor:
  # only one device
  - platform: dallas_temp
    name: "Temperature"
    id: temperature_sensor
    update_interval: 20s
  # specific address
  # - platform: dallas_temp
  #   address: 0x1234567812345628
  #   name: temperature2