substitutions:
  name: "jxd-r6-e1eth-lcd"
  friendly_name: JXD-R6-E1ETH-LCD
  device_description: JXD-R6-E1ETH-LCD v1
  version: 1.0.0
  # timezone: Asia/Shanghai

packages:
  display: !include ../include/jxd-r6-e1eth-display.yaml
  main: !include ../include/jxd-r6-e1eth-base.yaml
  ethernet: !include ../include/jxd-r6-eth.yaml
  eth_menu: !include ../include/jxd-r6-eth-menu-items.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  project:
    name: JetHub.JXD R6-E1ETH-LCD
    version: ${version}
  on_boot:
      priority: 600
      then:
        - delay: 200ms
        - pcf8563.read_time:
            id: pcf8563_time

external_components:
  - source:
      type: local 
      path: ../components
    components: [display_menu_base, graphical_display_menu]

http_request:

ota:
  - platform: http_request
    id: ota_http_request

dashboard_import:
  package_import_url: github://jethome-iot/esphome-configs/JXD/jxd-r6-e1eth-lcd.yaml@master
  import_full_config: true